### ISSUE TITLE
RasDialer throws unexpected exception for bad username/password.

### ISSUE THREAD

**Issue by jeff-winn** [winnster/DotRas#13]
- If we specify incorrect username, then `RasDialer.DialAsync()` throws `RasException` with `NativeErrorCode= 691`. That's correct. 
- But if we specify incorrect password, then occurs generic exception:
```
System.ArgumentException: The error code must be a positive value.
Parameter name: errorCode
   at DotRas.Internal.Services.ErrorHandling.RasGetErrorStringService.GetErrorString(Int32 errorCode)
   at DotRas.Internal.Policies.DefaultExceptionPolicy.Create(Int32 error)
   at DotRas.Internal.Services.Dialing.DefaultRasDialCallbackHandler.GuardErrorCodeMustBeZero(Int32 errorCode)
   at DotRas.Internal.Services.Dialing.DefaultRasDialCallbackHandler.OnCallback(IntPtr dwCallbackId, Int32 dwSubEntry, IntPtr hRasConn, UInt32 message, RasConnectionState connectionState, Int32 dwError, Int32 dwExtendedError)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleRunner.Program.<ConnectAsync>d__8.MoveNext() 
```
_Originally posted by @mogikanin in https://github.com/winnster/DotRas/issues/2#issuecomment-449821996_

**Comment by jeff-winn** [comment]
The exception thrown from this area seems to depend on which RAS server is being connected to. Some seem to just kill the connection without a meaningful response. 

Possible results seem to be:
- RasException with 691 error code indicating a username/password failure.
- Win32Exception with -2143157998 error code indicating an Unknown error occurred.
