### ISSUE TITLE
Enumerated Connection getstatus throws not support

### ISSUE THREAD

**Issue by Biztactix-Ryan** [winnster/DotRas#53]
G'day,

I've got an SSTP VPN connection and I can find it connected in enumerated connections, However the Get Status throws the following error, I had a little look, but couldn't find where the Unknown type is coming from, I'm guessing it just isn't supported at the moment.

Connection statistics works, So I'll use connected time in the mean time as that works

   ```
The endpoint type 'Unknown' is not supported.
at DotRas.Internal.Services.IPAddressConversionService.ConvertFromEndpoint(RASTUNNELENDPOINT endPoint) in C:\Repo\Expanded Libraries\DotRAS-Updated\src\DotRas\Internal\Services\IPAddressConversionService.cs:line 17
   at DotRas.Internal.Services.Connections.RasGetConnectStatusService.CreateLocalIPAddress(RASCONNSTATUS rasConnStatus) in C:\Repo\Expanded Libraries\DotRAS-Updated\src\DotRas\Internal\Services\Connections\RasGetConnectStatusService.cs:line 67
   at DotRas.Internal.Services.Connections.RasGetConnectStatusService.GetConnectionStatus(IRasConnection connection) in C:\Repo\Expanded Libraries\DotRAS-Updated\src\DotRas\Internal\Services\Connections\RasGetConnectStatusService.cs:line 38
   at DotRas.RasConnection.GetStatus() in C:\Repo\Expanded Libraries\DotRAS-Updated\src\DotRas\RasConnection.cs:line 135
```

**Comment by jeff-winn** [comment]
The reason you don't see where it's being set is because that particular function is using data returned from the Windows interop code. Windows is the source of the Unknown value.

Do you know whether the local address or remote address is returning the value unknown? There used to be a Wiki page that had detailed how to turn on diagnostic logging but it seems to have gone missing.

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.diagnostics>
    <sources>
      <source name="DotRas" switchValue="All">
        <listeners>
          <!-- Add your listeners here -->
        </listeners>
      </source>
    </sources>
  </system.diagnostics>
</configuration>
```

Adding this to your configuration file will turn it on, just make sure you remember to configure your listeners. The interop data should get logged under the switch value mentioned above. Keep an eye out for RasGetConnectStatus, that's the API that's being used.

Just want to make sure that the API change I make won't break something downstream by providing a NULL reference.

**Comment by jeff-winn** [comment]
I'm betting it's the remote endpoint, most likely where you're connecting just isn't telling you the IP address.

**Comment by Biztactix-Ryan** [comment]
It's because we turn off the default gateway on the VPN connection on purpose, We use routing to use the connection

So that will be the one.

**Comment by Biztactix-Ryan** [comment]
Thanks for the code update

**Comment by jeff-winn** [comment]
You’re welcome!
