### ISSUE TITLE
DotRas.RasException (623)

### ISSUE THREAD

**Issue by BG243021** [winnster/DotRas#97]
When I run DialConnection in 1. Examples, I got an exception :
DotRas.RasException (623): The system cannot find the phone book entry for this connection。
   at DotRas.Internal.Services.Security.RasGetEapUserDataService.TryUnsafeGetEapUserData(IntPtr impersonationToken, String entryName, String phoneBookPath, RASEAPINFO& eapInfo) in E:\VPN\DotRas-master\src\DotRas\Internal\Services\Security\RasGetEapUserDataService.cs:line 55
   at DotRas.Internal.Services.Dialing.RasDialExtensionsBuilder.Build(RasDialContext context) in E:\VPN\DotRas-master\src\DotRas\Internal\Services\Dialing\RasDialExtensionsBuilder.cs:line 42
   at DotRas.Internal.Services.Dialing.RasDialService.ConvertToRasDialExtensions(RasDialContext context) in E:\VPN\DotRas-master\src\DotRas\Internal\Services\Dialing\RasDialService.cs:line 157
   at DotRas.Internal.Services.Dialing.RasDialService.BeginDial(RasDialContext context) in E:\VPN\DotRas-master\src\DotRas\Internal\Services\Dialing\RasDialService.cs:line 116
   at DotRas.Internal.Services.Dialing.RasDialService.DialAsync(RasDialContext context) in E:\VPN\DotRas-master\src\DotRas\Internal\Services\Dialing\RasDialService.cs:line 61
   at DotRas.RasDialer.ConnectAsync(CancellationToken cancellationToken) in E:\VPN\DotRas-master\src\DotRas\RasDialer.cs:line 134
   at DotRas.RasDialer.Connect(CancellationToken cancellationToken) in E:\VPN\DotRas-master\src\DotRas\RasDialer.cs:line 101
   at DotRas.RasDialer.Connect() in E:\VPN\DotRas-master\src\DotRas\RasDialer.cs:line 85
   at DialConnection.Program.Run() in E:\VPN\DotRas-master\examples\DialConnection\Program.cs:line 55
   at DialConnection.Program.Main() in E:\VPN\DotRas-master\examples\DialConnection\Program.cs:line 16

**Comment by BG243021** [comment]
win-10 debug, I just fill in the EntryName and Credentials, 
and I see the PhoneBookPath is "C:\Users\BG243\AppData\Roaming\Microsoft\Network\Connections\Pbk\rasphone.pbk".
actually, i just find "rasphone.pbk" under "C:\Users\BG243\AppData\Roaming\Microsoft\Network\Connections\Pbk\_hiddenPbk" but when i change the path to "C:\Users\BG243\AppData\Roaming\Microsoft\Network\Connections\Pbk\_hiddenPbk\rasphone.pbk"  it still not work. 
Whether I did something wrong? please help.

**Comment by jeff-winn** [comment]
The RasDialer class must know the entry name and the full path to the file containing the entry in order to function.

So a couple questions:
- Do you have the full path to the file (including the filename) set on the PhoneBookPath property on RasDialer?
- If you double click the hidden PBK file, and use the Microsoft UI to dial it, does it too have an issue?
- Is the hidden pbk actually a hidden file or contained within a hidden directory? Windows may not like if the file is hidden on disk.

**Comment by jeff-winn** [comment]
From a quick test, Windows (on my machine) doesn't appear to have a problem with the 3rd item of the directory and/or rasphone.pbk file being used. So it's likely not the hidden attribute being applied.

**Comment by BG243021** [comment]
thanks jeff,
    thanks for your solution. Finally, I find the problem is I`m not create the entry, RasDialer can`t find the entry when connect. But I`m not find RasPhoneBook class in DotRas.for.Win10. Should I use DotRas.for.Win8(1.3.0) to create?

**Comment by jeff-winn** [comment]
I haven't had time to work on the RasPhoneBook replacement in DotRas 2.x, but I also know there are compatibility issues with the 1.x versions if you're trying to target Windows 10.

The PBK file should be deployable across machines (assuming they have the same hardware, and depending on what kind of entry you're trying to use). So if you don't need to auto-create the phonebook and the entry, you might be able to just setup your pbk file once and deploy it.
